config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => "posts#index"

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true 
	validates :body, presence: true 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 

	def index 
		@posts = Post.all.order('created_at DESC')
	end 

	def new 
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else 
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to action: "index"
	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	 <div class="top_nav">
  		<ul>
  			<li><%= link_to "Home", :controller => "posts", :action => "index"%></li>
        <li><%= link_to "New Post", :controller => "posts", :action => "new"%></li>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>
<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%=f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1> Hello. </h1>
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post%></h2>
			<h3> <%= post.created_at.strftime("%d %b. %Y") %> </h3>
			<p class="body"><%= post.body %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1> New Post<h1>

<%= form_for @post, url: posts_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%=f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1 class="title"><%= @post.title %></h1>

<p class="date">
	Posted <%= time_ago_in_words(@post.created_at) %> ago
</p>

<p class="body">
	<%= @post.body %>
</p>

<%= link_to 'Edit', :controller => "posts", :action => "edit" %>
<%= link_to 'Delete',  { action: :destroy, id: @post.id }, method: :delete, data: { confirm: 'Are you sure?' } %></td>